# Generated by Django 3.0.1 on 2020-01-23 03:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('date_created', models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 23, 3, 53, 1, 240374))),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_order', models.DateField()),
                ('cus_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('food_id', models.ManyToManyField(to='customer.Food')),
            ],
        ),
    ]
