# Generated by Django 3.0.1 on 2020-01-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='cus_id',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cus_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
