# Generated by Django 3.0.1 on 2020-01-23 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_category_customer_favourites_food_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 23, 8, 36, 59, 611084)),
        ),
    ]
