# Generated by Django 3.0.1 on 2020-01-23 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200123_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 23, 9, 48, 49, 669376)),
        ),
    ]
