# Generated by Django 3.0.1 on 2020-01-23 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200123_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 1, 23, 9, 49, 37, 500161)),
        ),
    ]
