# Generated by Django 3.0.1 on 2020-02-06 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('address', models.CharField(max_length=30)),
                ('contact', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='uploads/')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Customer')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Customer')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
    ]
